jobs:
  include:
    - stage: deploy
      name : ubuntu 16.04
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t ctf:16.04 -f ./16.04/Dockerfile .
      - docker images
      - docker tag ctf $DOCKER_USERNAME/ctf
      - docker push $DOCKER_USERNAME/ctf
    - stage: deploy
      name : ubuntu 18.04
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t ctf:18.04 -f ./18.04/Dockerfile .
      - docker images
      - docker tag ctf $DOCKER_USERNAME/ctf
      - docker push $DOCKER_USERNAME/ctf